apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed
  labels:
    service: udagram-api-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udagram-api-feed
  template:
    metadata:
      labels:
        service: udagram-api-feed
    spec:
      containers:
        - name: udagram-api-feed
          image: khomeafegbua/udagram-api-feed:latest
          resources:
            requests:
              memory: '64Mi'
              cpu: '250m'
            limits:
              memory: '1024Mi'
              cpu: '500m'
          env:
            - name: http://localhost:8100
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: http://localhost:8100
            - name: lastchance-dev
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: lastchance-dev
            - name: default
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: default
            - name: us-east-1
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: us-east-1
            - name: hellow
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: hellow
            - name: postgres
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: postgres
            - name: khome-1.cr9cvmnikkno.us-east-1.rds.amazonaws.com
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: khome-1.cr9cvmnikkno.us-east-1.rds.amazonaws.com
            - name: khomeafegbua
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: khomeafegbua
            - name: khome-1
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: khome-1
      restartPolicy: Always
